spring:
  profiles:
    active: pro,redis
  resources:
    static-locations: ["/templates/","/static/"]
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: LEGACYHTML5
    enabled: true
    prefix: classpath:/templates/
